export function getDom() {
  return {
    linkInput: document.querySelector('#link-input'),
    fileInput: document.querySelector('#file-input'),
    importTextButton: document.querySelector('#import-text-button'),
    chooseFolderButton: document.querySelector('#choose-folder-button'),
    saveStatus: document.querySelector('#save-status'),
    importReport: document.querySelector('#import-report'),
    queueList: document.querySelector('#queue-list'),
    playerStatus: document.querySelector('#player-status'),
    video: document.querySelector('#video-element'),
    youtubeHost: document.querySelector('#youtube-host'),
    previousButton: document.querySelector('#previous-button'),
    nextButton: document.querySelector('#next-button'),
    cueStartInput: document.querySelector('#cue-start-input'),
    cueEndInput: document.querySelector('#cue-end-input'),
    responseStartInput: document.querySelector('#response-start-input'),
    responseEndInput: document.querySelector('#response-end-input'),
    cueActorInput: document.querySelector('#cue-actor-input'),
    candidateRecipientInput: document.querySelector('#candidate-recipient-input'),
    cueTypeSelect: document.querySelector('#cue-type-select'),
    accessLabelSelect: document.querySelector('#access-label-select'),
    responseLabelSelect: document.querySelector('#response-label-select'),
    responseTypeSelect: document.querySelector('#response-type-select'),
    cueResponseLinkSelect: document.querySelector('#cue-response-link-select'),
    evidenceSpansInput: document.querySelector('#evidence-spans-input'),
    episodeDescriptionInput: document.querySelector('#episode-description-input'),
    ambiguityLabelSelect: document.querySelector('#ambiguity-label-select'),
    saveInteractionButton: document.querySelector('#save-interaction-button'),
    eraseInteractionButton: document.querySelector('#erase-interaction-button'),
    useCueResponseEvidenceButton: document.querySelector('#use-cue-response-evidence-button'),
    timeCaptureButtons: document.querySelectorAll('[data-time-target]'),
    interactionEpisodesList: document.querySelector('#interaction-episodes-list')
  };
}
